version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 3000:3000
    command: nodemon -L index.js
    networks:
      - local
    links: 
      - db
    volumes:
      - .:/app
  db:
    image: mongo:latest
    ports: 
      - 27017:27017
    networks:
      - local
    volumes:
      - ../data-volumes/db:/data/db
  redis: 
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - local
    volumes: 
      - ../data-volumes/redis:/data/redis
    
networks:
  local: